# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aiVx9A8pVAXYDtvE-qKK9oambiK8iCl7
"""

import streamlit as st
import joblib

@st.cache_resource
def load_models():
    lr_model = joblib.load("logistic_model.pkl")
    nb_model = joblib.load("naive_bayes_model.pkl")
    return lr_model, nb_model

@st.cache_resource
def load_vectorizer():
    return joblib.load("vectorizer.pkl")

@st.cache_resource
def load_label_encoder():
    return joblib.load("label_encoder.pkl")

# Load resources
lr_model, nb_model = load_models()
vectorizer = load_vectorizer()
label_encoder = load_label_encoder()

# UI elements
st.title("📊 Sentiment Analysis on Reviews")

review_text = st.text_area("📝 Enter your review text:")
model_choice = st.selectbox("Choose model:", ["Logistic Regression", "Naive Bayes"])

# Predict
if st.button("🔍 Predict"):
    if not review_text.strip():
        st.warning("Please enter review text.")
    else:
        vect_input = vectorizer.transform([review_text])
        model = lr_model if model_choice == "Logistic Regression" else nb_model
        prediction = model.predict(vect_input)[0]
        sentiment = label_encoder.inverse_transform([prediction])[0]
        st.success(f"Predicted Sentiment: {sentiment}")